// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: obj_reid_feat.prototxt

#ifndef PROTOBUF_obj_5freid_5ffeat_2eprototxt__INCLUDED
#define PROTOBUF_obj_5freid_5ffeat_2eprototxt__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_obj_5freid_5ffeat_2eprototxt();
void protobuf_InitDefaults_obj_5freid_5ffeat_2eprototxt();
void protobuf_AssignDesc_obj_5freid_5ffeat_2eprototxt();
void protobuf_ShutdownFile_obj_5freid_5ffeat_2eprototxt();

class face_feat_entry;
class human_feat_entry;

// ===================================================================

class face_feat_entry : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:face_feat_entry) */ {
 public:
  face_feat_entry();
  virtual ~face_feat_entry();

  face_feat_entry(const face_feat_entry& from);

  inline face_feat_entry& operator=(const face_feat_entry& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const face_feat_entry& default_instance();

  static const face_feat_entry* internal_default_instance();

  void Swap(face_feat_entry* other);

  // implements Message ----------------------------------------------

  inline face_feat_entry* New() const { return New(NULL); }

  face_feat_entry* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const face_feat_entry& from);
  void MergeFrom(const face_feat_entry& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(face_feat_entry* other);
  void UnsafeMergeFrom(const face_feat_entry& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated float reid_face_feat = 1;
  int reid_face_feat_size() const;
  void clear_reid_face_feat();
  static const int kReidFaceFeatFieldNumber = 1;
  float reid_face_feat(int index) const;
  void set_reid_face_feat(int index, float value);
  void add_reid_face_feat(float value);
  const ::google::protobuf::RepeatedField< float >&
      reid_face_feat() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_reid_face_feat();

  // @@protoc_insertion_point(class_scope:face_feat_entry)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField< float > reid_face_feat_;
  friend void  protobuf_InitDefaults_obj_5freid_5ffeat_2eprototxt_impl();
  friend void  protobuf_AddDesc_obj_5freid_5ffeat_2eprototxt_impl();
  friend void protobuf_AssignDesc_obj_5freid_5ffeat_2eprototxt();
  friend void protobuf_ShutdownFile_obj_5freid_5ffeat_2eprototxt();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<face_feat_entry> face_feat_entry_default_instance_;

// -------------------------------------------------------------------

class human_feat_entry : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:human_feat_entry) */ {
 public:
  human_feat_entry();
  virtual ~human_feat_entry();

  human_feat_entry(const human_feat_entry& from);

  inline human_feat_entry& operator=(const human_feat_entry& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const human_feat_entry& default_instance();

  static const human_feat_entry* internal_default_instance();

  void Swap(human_feat_entry* other);

  // implements Message ----------------------------------------------

  inline human_feat_entry* New() const { return New(NULL); }

  human_feat_entry* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const human_feat_entry& from);
  void MergeFrom(const human_feat_entry& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(human_feat_entry* other);
  void UnsafeMergeFrom(const human_feat_entry& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated float reid_feat = 1;
  int reid_feat_size() const;
  void clear_reid_feat();
  static const int kReidFeatFieldNumber = 1;
  float reid_feat(int index) const;
  void set_reid_feat(int index, float value);
  void add_reid_feat(float value);
  const ::google::protobuf::RepeatedField< float >&
      reid_feat() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_reid_feat();

  // @@protoc_insertion_point(class_scope:human_feat_entry)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField< float > reid_feat_;
  friend void protobuf_InitDefaults_obj_5freid_5ffeat_2eprototxt_impl();
  friend void protobuf_AddDesc_obj_5freid_5ffeat_2eprototxt_impl();
  friend void protobuf_AssignDesc_obj_5freid_5ffeat_2eprototxt();
  friend void protobuf_ShutdownFile_obj_5freid_5ffeat_2eprototxt();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<human_feat_entry> human_feat_entry_default_instance_;

// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// face_feat_entry

// repeated float reid_face_feat = 1;
inline int face_feat_entry::reid_face_feat_size() const {
  return reid_face_feat_.size();
}
inline void face_feat_entry::clear_reid_face_feat() {
  reid_face_feat_.Clear();
}
inline float face_feat_entry::reid_face_feat(int index) const {
  // @@protoc_insertion_point(field_get:face_feat_entry.reid_face_feat)
  return reid_face_feat_.Get(index);
}
inline void face_feat_entry::set_reid_face_feat(int index, float value) {
  reid_face_feat_.Set(index, value);
  // @@protoc_insertion_point(field_set:face_feat_entry.reid_face_feat)
}
inline void face_feat_entry::add_reid_face_feat(float value) {
  reid_face_feat_.Add(value);
  // @@protoc_insertion_point(field_add:face_feat_entry.reid_face_feat)
}
inline const ::google::protobuf::RepeatedField< float >&
face_feat_entry::reid_face_feat() const {
  // @@protoc_insertion_point(field_list:face_feat_entry.reid_face_feat)
  return reid_face_feat_;
}
inline ::google::protobuf::RepeatedField< float >*
face_feat_entry::mutable_reid_face_feat() {
  // @@protoc_insertion_point(field_mutable_list:face_feat_entry.reid_face_feat)
  return &reid_face_feat_;
}

inline const face_feat_entry* face_feat_entry::internal_default_instance() {
  return &face_feat_entry_default_instance_.get();
}
// -------------------------------------------------------------------

// human_feat_entry

// repeated float reid_feat = 1;
inline int human_feat_entry::reid_feat_size() const {
  return reid_feat_.size();
}
inline void human_feat_entry::clear_reid_feat() {
  reid_feat_.Clear();
}
inline float human_feat_entry::reid_feat(int index) const {
  // @@protoc_insertion_point(field_get:human_feat_entry.reid_feat)
  return reid_feat_.Get(index);
}
inline void human_feat_entry::set_reid_feat(int index, float value) {
  reid_feat_.Set(index, value);
  // @@protoc_insertion_point(field_set:human_feat_entry.reid_feat)
}
inline void human_feat_entry::add_reid_feat(float value) {
  reid_feat_.Add(value);
  // @@protoc_insertion_point(field_add:human_feat_entry.reid_feat)
}
inline const ::google::protobuf::RepeatedField< float >&
human_feat_entry::reid_feat() const {
  // @@protoc_insertion_point(field_list:human_feat_entry.reid_feat)
  return reid_feat_;
}
inline ::google::protobuf::RepeatedField< float >*
human_feat_entry::mutable_reid_feat() {
  // @@protoc_insertion_point(field_mutable_list:human_feat_entry.reid_feat)
  return &reid_feat_;
}

inline const human_feat_entry* human_feat_entry::internal_default_instance() {
  return &human_feat_entry_default_instance_.get();
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_obj_5freid_5ffeat_2eprototxt__INCLUDED
